---
kind: pipeline
name: wordpress-docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: ktruckenmiller/ecs-wordpress-migrator
      context: deployment
      dockerfile: deployment/Dockerfile
      username:
        from_secret: username
      password:
        from_secret: password
